---
- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: 51.250.15.115
  tasks:
   - name: Add unit file for Puma
     copy:
       src: files/puma.service
       dest: /etc/systemd/system/puma.service
     notify: reload puma
   - name: Add config for DB connection
     template:
       src: templates/db_config.j2
       dest: /home/ubuntu/db_config
   - name: enable puma
     systemd: name=puma enabled=yes
  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
